version: '3'
services:

  db:
    image: postgres:15-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123ewqasd
      - POSTGRES_USER=apcoa_user
      - POSTGRES_DB=apcoa_fk
    ports:
      - "5432:5432"

volumes:
  pg_data:
